### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by ctala** [chrisg2204/bitly#1]
Al parecer no incluíste el package.json, por lo que el servicio falla al iniciar.

npm ERR! path /home/ctala/checkProfiles/bitly/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/home/ctala/checkProfiles/bitly/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ctala/.npm/_logs/2018-03-15T16_09_57_860Z-debug.log

**Comment by chrisg2204** [comment]
Commit and fix, gimme a min

**Comment by chrisg2204** [comment]
Resulto en la siguiente revision 3d6680a65d8727c67d406b51565b7342921f3dd7
